server:
  port: 8080
  tomcat:
    threads:
      max: 200
    accept-count: 200
    max-connections: 2000
    connection-timeout: 30000

spring:
  application:
    name: demo1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    eu.europa.esig.dss: WARN
    org.apache.pdfbox: WARN

keystore:
  test: testsign
